# Generated by Django 4.1.13 on 2023-12-04 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_create_post_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=250, unique_for_date=models.DateField(default=django.utils.timezone.now)),
        ),
    ]
